const datasetKey = 'general';
const defaultData = [
  { "question": "Subject: Following up. Hi, just checking in on the proposal I sent over last week. Do you have any questions?", "answer": "" },
  { "question": "Subject: Reschedule. I have a conflict for our meeting tomorrow at 2 PM. Can we move it to Thursday at the same time?", "answer": "" },
  { "question": "Subject: Intro. Hi Safwan, I wanted to introduce you to John, who handles our marketing. John, Safwan runs Fylint.", "answer": "" },
  { "question": "Subject: Out of Office. I will be out of the office starting Friday and returning next Wednesday. For urgent matters, please contact support.", "answer": "" },
  { "question": "Subject: Quick question. What time is the team sync happening today?", "answer": "" },
  { "question": "Subject: Invoice attached. Please find attached the invoice for services rendered in August. Let me know if you need anything else.", "answer": "" },
  { "question": "Subject: Coffee chat. Hey, I'll be in your city next week. Would you be open to grabbing a coffee on Tuesday morning?", "answer": "" },
  { "question": "Subject: Deck review. Can you take a quick look at the attached slide deck before I present it tomorrow?", "answer": "" },
  { "question": "Subject: Re: Next steps. Thanks for the call. Let's proceed with option B. Send over the contract when you can.", "answer": "" },
  { "question": "Subject: Checking in. Haven't heard from you in a while, just wanted to see how the new project is going.", "answer": "" },
  { "question": "Subject: Re: Payment setup. We need you to fill out this W-9 form before we can process the first invoice.", "answer": "" },
  { "question": "Subject: Happy Holidays! Wishing you and your team a great holiday season. Looking forward to working together next year.", "answer": "" },
  { "question": "Subject: Re: Update. The deployment has been delayed by two days due to some unexpected bugs. I'll keep you posted.", "answer": "" },
  { "question": "Subject: Access request. Can you please grant me view access to the Google Analytics dashboard?", "answer": "" },
  { "question": "Subject: Missing attachment. Hi, I think you forgot to attach the file in your last email.", "answer": "" },
  { "question": "Subject: Re: Feedback. I left a few comments on the Google Doc. Let me know what you think of the suggested changes.", "answer": "" },
  { "question": "Subject: Let's connect. I saw your recent post on LinkedIn and really liked your perspective. Would love to connect and chat.", "answer": "" },
  { "question": "Subject: Re: Availability. I am free next Tuesday between 1 PM and 4 PM EST. Do any of those times work for a call?", "answer": "" },
  { "question": "Subject: Thank you. Just wanted to say thanks again for your help with the presentation yesterday. It went really well.", "answer": "" },
  { "question": "Subject: Re: Contract renewal. Our annual contract is up for renewal next month. Can we schedule a quick chat to discuss?", "answer": "" },
  { "question": "Subject: Re: Question about pricing. Do you offer any discounts for non-profits or early-stage startups?", "answer": "" },
  { "question": "Subject: Re: Onboarding. Welcome to the team! Your first orientation session is scheduled for Monday at 10 AM.", "answer": "" },
  { "question": "Subject: Bug report. Hi, the login button on the homepage seems to be broken on mobile devices. Can someone look into this?", "answer": "" },
  { "question": "Subject: Re: Recommendation. Can you recommend a good tool for managing social media scheduling? We're looking to switch.", "answer": "" },
  { "question": "Subject: Congratulations! Saw the news about the recent funding round. Huge congrats to you and the team!", "answer": "" },
  { "question": "Subject: Action Required. Please review the updated terms of service by Friday to avoid any account interruptions.", "answer": "" },
  { "question": "Subject: Re: Brainstorming session. Can we push our brainstorm session to next week? I need more time to gather some data.", "answer": "" },
  { "question": "Subject: Request for time off. I would like to request PTO for next Thursday and Friday. All my projects are currently up to date.", "answer": "" },
  { "question": "Subject: Reminder: Timesheets due. A quick reminder to submit your timesheets by 5 PM today.", "answer": "" },
  { "question": "Subject: Re: Support ticket #4091. The issue has been resolved on our end. Please clear your cache and try again.", "answer": "" },
  { "question": "Subject: Invitation to speak. We are hosting a panel on digital marketing next month and would love to have you as a guest speaker.", "answer": "" },
  { "question": "Subject: Decline invite. Thanks for the invitation, but I won't be able to make it to the event due to prior commitments.", "answer": "" },
  { "question": "Subject: Re: Follow up on interview. Thank you for taking the time to interview with us. We will get back to you with a decision by Friday.", "answer": "" },
  { "question": "Subject: Re: Project timeline. The client is asking if we can deliver the first draft a week earlier than planned. Is that feasible?", "answer": "" },
  { "question": "Subject: Need approval. Please review the attached budget for Q3 and let me know if it's approved.", "answer": "" },
  { "question": "Subject: Checking references. We are considering a candidate for a role and they listed you as a reference. Could we schedule a brief call?", "answer": "" },
  { "question": "Subject: Apology for the delay. Sorry for the delayed response, I've been traveling. I will review this and get back to you tomorrow.", "answer": "" },
  { "question": "Subject: Re: Partnership inquiry. Thanks for reaching out. What exactly are you looking for in a partner for this initiative?", "answer": "" },
  { "question": "Subject: Re: Question. Yes, that makes sense. Let's proceed as you suggested.", "answer": "" },
  { "question": "Subject: Re: Can you hop on a quick call? I'm in back-to-back meetings today. Can we talk tomorrow morning instead?", "answer": "" },
  { "question": "Subject: Updated contact info. Please note my new phone number is 555-0198. My email remains the same.", "answer": "" },
  { "question": "Subject: Re: Urgent! The server is down. We are aware of the issue and the engineering team is working on a fix right now.", "answer": "" },
  { "question": "Subject: Re: Newsletter sponsorship. We are interested in sponsoring your newsletter. Can you send over your current rates and audience stats?", "answer": "" },
  { "question": "Subject: Canceling my subscription. Please cancel my account effective immediately. Thank you.", "answer": "" },
  { "question": "Subject: Refund request. I was accidentally double-charged for my last purchase. Can you please issue a refund for the duplicate charge?", "answer": "" },
  { "question": "Subject: Re: Checking in. We've decided to go in a different direction for this project. We appreciate your time and proposals.", "answer": "" },
  { "question": "Subject: Re: Welcome! Thanks for the warm welcome! Looking forward to meeting everyone.", "answer": "" },
  { "question": "Subject: Re: Follow up. I'm still waiting to hear back from legal on this. I'll let you know as soon as I have an update.", "answer": "" },
  { "question": "Subject: Re: Feedback request. Overall it looks great, but could we make the logo slightly larger on the homepage?", "answer": "" },
  { "question": "Subject: Re: Next week's agenda. Can we add a 10-minute block to discuss the upcoming Q4 goals during the meeting?", "answer": "" }
];
