const datasetKey = 'ima';
const defaultData = [
  { "question": "Subject: Re: Sponsorship. Hi Safwan, we might be interested. Can you send over a media kit and some case studies of past tech campaigns?", "answer": "" },
  { "question": "Subject: Partnership. Hi, what is your standard rate for a dedicated 60s integration?", "answer": "" },
  { "question": "Subject: Re: Outreach. Thanks for reaching out. We don't have any budget for influencer marketing this quarter. Try back in Q3.", "answer": "" },
  { "question": "Subject: Collab. Hey, we'd love to work with you but we only do affiliate commission right now (no flat fee). Is that something you'd consider?", "answer": "" },
  { "question": "Subject: Re: Fylint. Hi Safwan, who are the exact creators you represent in the cybersecurity space? Can you share a roster?", "answer": "" },
  { "question": "Subject: Re: Sponsorship. We are interested, but our maximum budget per integration is $500. Can you work with that?", "answer": "" },
  { "question": "Subject: Re: Brand Deal. Can we get perpetual usage rights and whitelisting access included in the base rate?", "answer": "" },
  { "question": "Subject: Re: Outreach. Hi Safwan, we only work with creators who have a primarily US-based audience (80%+). What are your creators' demographics?", "answer": "" },
  { "question": "Subject: Campaign. We need the video to go live next week. Is it possible to rush the production timeline?", "answer": "" },
  { "question": "Subject: Re: Partnership. Do you offer guarantees on views or clicks for these integrations?", "answer": "" },
  { "question": "Subject: Draft review. Hey Safwan, we reviewed the script draft. We need the creator to add 3 more talking points about our new feature.", "answer": "" },
  { "question": "Subject: Re: Outreach. This sounds interesting. Can we jump on a quick 15-minute call tomorrow to discuss?", "answer": "" },
  { "question": "Subject: Re: Contract. We noticed the contract says payment is Net-30. We only do Net-60. Is that acceptable?", "answer": "" },
  { "question": "Subject: Deliverable. Hi, the creator forgot to include our tracking link in the description for the first 12 hours. How do we resolve this?", "answer": "" },
  { "question": "Subject: Re: Pitch. We love the creator, but they recently worked with our direct competitor 2 months ago. Does your contract include exclusivity?", "answer": "" },
  { "question": "Subject: Re: Collaboration. Hey Safwan, what’s the difference between working with your agency versus just emailing the creator directly?", "answer": "" },
  { "question": "Subject: Performance. The recent integration didn't perform as well as we hoped in terms of conversions. Any thoughts on what went wrong?", "answer": "" },
  { "question": "Subject: Re: Sponsorship. Can you send over an example of a dedicated video vs a 60-second integration so we can compare the value?", "answer": "" },
  { "question": "Subject: Rates. The creator's CPM seems really high compared to industry standard. Are these rates negotiable?", "answer": "" },
  { "question": "Subject: Re: Outreach. We're interested. Send over the contract and we'll get it signed today.", "answer": "" },
  { "question": "Subject: Re: Creator Pitch. Hey Safwan, I'm a creator and I'm interested in joining Fylint. What percentage do you take as an agency?", "answer": "" },
  { "question": "Subject: Brand Deal. Hi Safwan, the brand wants to change the script completely after I already filmed it. What should I do?", "answer": "" },
  { "question": "Subject: Re: Outreach. I don't want to do dedicated videos, only 60-90 second mid-roll integrations. Can you pitch me for those?", "answer": "" },
  { "question": "Subject: Re: Payment. The brand was supposed to pay last week (Net-30) and I still haven't received the wire. Can you chase them?", "answer": "" },
  { "question": "Subject: Campaign brief. Hey Safwan, the brand's talking points feel really unnatural for my channel. Can I rewrite them in my own words?", "answer": "" },
  { "question": "Subject: Re: Pitch. I'm getting a lot of views right now on Shorts. Do brands pay for YouTube Shorts sponsorships?", "answer": "" },
  { "question": "Subject: Re: Collab. The brand asked me to post a TikTok alongside the YouTube integration for free. Should I say no?", "answer": "" },
  { "question": "Subject: Re: Sponsorship. I don't want to promote VPNs or crypto. Will this be a problem for getting deals?", "answer": "" },
  { "question": "Subject: Timeline. I'm sick and can't film this weekend. Can we push the brand's deadline back by 4 days?", "answer": "" },
  { "question": "Subject: Re: Metrics. The brand is asking for a screenshot of my YouTube studio analytics. Is it safe to share that?", "answer": "" },
  { "question": "Subject: Re: Follow up. Hey Safwan, we loved the last integration. We want to book a 3-video package. Do you offer bulk discounts?", "answer": "" },
  { "question": "Subject: Re: Product Seeding. We don't have cash budget, but we'd love to send the creator our $2,000 laptop in exchange for a review. Would they accept?", "answer": "" },
  { "question": "Subject: Approvals. We need to have 2 rounds of revision rights on the video before it goes live. Is that standard?", "answer": "" },
  { "question": "Subject: Exclusivity. We need 3 months of category exclusivity following the video upload. Does this increase the rate?", "answer": "" },
  { "question": "Subject: Re: Pitch. Hi Safwan, we prefer to run our own UGC ads. Can we pay the creator just to film raw footage, no posting required?", "answer": "" },
  { "question": "Subject: Re: Revisions. The creator mispronounced our brand name twice in the ad read. Can they re-record those sections?", "answer": "" },
  { "question": "Subject: Re: Outreach. We are a B2B SaaS company. Do your creators have audiences that actually buy B2B software?", "answer": "" },
  { "question": "Subject: FTC. Does the creator verbally disclose the sponsorship, or just put #ad in the title?", "answer": "" },
  { "question": "Subject: Re: Rates. If we book a dedicated video, can we cut it down into 15-second clips for our Instagram ads?", "answer": "" },
  { "question": "Subject: Whitelisting. We want to run Spark Ads on TikTok from the creator's handle. How much extra is that per month?", "answer": "" },
  { "question": "Subject: Re: Creator joining. Hey Safwan, I currently have another manager. How easy is it to transition over to Fylint?", "answer": "" },
  { "question": "Subject: Product arrival. The brand still hasn't shipped the physical product and the draft is due in 3 days. What do we do?", "answer": "" },
  { "question": "Subject: Re: Script. The brief requires me to wear a specific outfit (suit and tie) for the ad read. I usually wear casual clothes on my channel. Thoughts?", "answer": "" },
  { "question": "Subject: Re: Draft. The brand rejected my draft because they said my energy was 'too low'. Should I push back or just re-record?", "answer": "" },
  { "question": "Subject: Payment terms. Can I get 50% upfront before I start filming? I've been burned by brands before.", "answer": "" },
  { "question": "Subject: Re: Outreach. I've only got 5,000 subscribers but my engagement is really high. Can you still get me sponsorships?", "answer": "" },
  { "question": "Subject: Usage. The brand used my face on their homepage without asking. My contract only said social media ads. How do we handle this?", "answer": "" },
  { "question": "Subject: Re: Pitch. The brand is asking me to buy the product first and they will reimburse me. Is this a scam?", "answer": "" },
  { "question": "Subject: Re: Contract. The brand's contract says they own the copyright to my entire video, not just the ad segment. Please review.", "answer": "" },
  { "question": "Subject: Deliverables. The brand is asking me to add a dedicated pinned comment. Do I charge extra for that?", "answer": "" },
  { "question": "Subject: Re: Brand Pitch. Hi Safwan, our app is currently only available on iOS. Are the creator's viewers mostly Android or Apple?", "answer": "" },
  { "question": "Subject: Re: Campaign. We’d like the creator to wear our branded t-shirt during the integration. Will you ship it to them?", "answer": "" },
  { "question": "Subject: Re: Analytics. The video has been live for 48 hours. When can we expect the first analytics report?", "answer": "" },
  { "question": "Subject: Re: Pitch. We love the pitch, but our legal team requires all creators to sign our NDA before we reveal the product details.", "answer": "" },
  { "question": "Subject: Payment. Can we pay via PayPal instead of Bank Transfer/Wire? Our finance team prefers it.", "answer": "" },
  { "question": "Subject: Re: Sponsorship. We'd like to do a performance-based test first. We'll pay a flat $200 + $10 per conversion. If it goes well, we'll do a flat rate next time.", "answer": "" },
  { "question": "Subject: Re: Draft. We need the creator to remove a joke they made right before our ad read. It doesn't align with our brand safety guidelines.", "answer": "" },
  { "question": "Subject: Re: Outreach. We are launching a new product next Friday and need 5 creators to post on the exact same day. Can you accommodate?", "answer": "" },
  { "question": "Subject: Re: Creators. Do you have any creators in the Web3/Crypto space? We are a new hardware wallet.", "answer": "" },
  { "question": "Subject: Re: Rights. If we pay for 6 months of digital ad rights, does that include connected TV (Hulu, Roku) or just social media?", "answer": "" },
  { "question": "Subject: Re: Creator side. Hey Safwan, a brand I worked with 2 years ago just reached out to me directly bypassing Fylint. How should I respond?", "answer": "" },
  { "question": "Subject: Content strike. My video just got a community guidelines strike and was taken down, but the brand's ad was in it. What do we do about the brand?", "answer": "" },
  { "question": "Subject: Re: Revisions. The brand wants me to re-edit the video, but my editor already charged me for the final cut. Who pays for the extra edit?", "answer": "" },
  { "question": "Subject: Re: Pitch. Do you guys help with thumbnails and titles, or do you only handle the sponsorships?", "answer": "" },
  { "question": "Subject: Conflict. I just signed a deal with NordVPN through you, but Surfshark just emailed me directly offering double the money. Can I back out?", "answer": "" },
  { "question": "Subject: Re: Audience. My audience is mostly from India and the Philippines, but brands always want US/UK. How do we pitch my channel?", "answer": "" },
  { "question": "Subject: Re: Contract. The brand's contract has a non-disparagement clause that lasts forever. Should I be worried?", "answer": "" },
  { "question": "Subject: Live stream. A brand wants to sponsor my Twitch stream. How do we price a live integration compared to a YouTube video?", "answer": "" },
  { "question": "Subject: Free product. A company sent me a $500 microphone unsolicited and is now demanding I make a video about it. Am I legally obligated?", "answer": "" },
  { "question": "Subject: Re: Views. My last three videos tanked in views. Will this affect my current ongoing contracts with the brands we booked?", "answer": "" },
  { "question": "Subject: Re: Agency Intro. Hi Safwan, we are a PR agency representing [Major Brand]. We are looking to book 20 tech creators. Do you do agency-to-agency deals?", "answer": "" },
  { "question": "Subject: Re: Revisions. The creator's lighting in the ad read is very dark and grainy compared to the rest of the video. We need it reshot.", "answer": "" },
  { "question": "Subject: Re: Brief. We forgot to include a crucial legal disclaimer in the brief. The video is already live. Can the creator pin a comment with the disclaimer?", "answer": "" },
  { "question": "Subject: Re: Payment setup. Our vendor onboarding system requires a W-9 and a voided check. Can you provide these for Fylint?", "answer": "" },
  { "question": "Subject: Re: Strategy. We want to move away from 60-second integrations and do a \"sponsored by\" 10-second bumper at the start. How much cheaper is that?", "answer": "" },
  { "question": "Subject: Re: Pitch. We love the creator, but we noticed they use a lot of profanity in their videos. Can they keep it PG for the video our ad is in?", "answer": "" },
  { "question": "Subject: Re: Integration. The creator placed our ad at the 15-minute mark of a 20-minute video. We usually request it in the first 5 minutes. Is it too late to change?", "answer": "" },
  { "question": "Subject: Re: Creator Roster. Do you represent any female tech creators? We are running a Women in STEM campaign next month.", "answer": "" },
  { "question": "Subject: Re: Rights. We don't want to run ads with the footage, we just want to post the clip organically on our brand Twitter. Do we still need to pay for usage rights?", "answer": "" },
  { "question": "Subject: Re: Cancelation. Our marketing budget just got slashed and we need to cancel the campaign. The contract is signed but the creator hasn't filmed yet. Can we kill it?", "answer": "" },
  { "question": "Subject: Re: Creator issue. I accidentally uploaded the video early and forgot to send the draft to the brand for approval first. It already has 10k views. What do I do?", "answer": "" },
  { "question": "Subject: Re: Link in bio. The brand wants me to put their link in my Instagram bio for 30 days. I usually only do YouTube links. What's the going rate for a bio link?", "answer": "" },
  { "question": "Subject: Re: Metrics. The brand wants me to share my average view duration and click-through rate for my last 5 videos before they commit. Should I?", "answer": "" },
  { "question": "Subject: Re: Giveaway. The brand wants to do a giveaway on my channel, but they want me to handle shipping the prize to the winner. Is that normal?", "answer": "" },
  { "question": "Subject: Re: Long term. I really liked the product from the last integration. Can we pitch them on a 12-month brand ambassadorship?", "answer": "" },
  { "question": "Subject: Re: Brand safety. I'm planning to make a highly critical video about a major tech company. Will this scare off our current sponsors?", "answer": "" },
  { "question": "Subject: Re: Pitch. A brand reached out to me on Twitter DM. Do I just forward it to you to handle?", "answer": "" },
  { "question": "Subject: Re: Deliverables. The brand is asking for the raw unedited video files from the shoot, not just the final cut. Should I give it to them?", "answer": "" },
  { "question": "Subject: Re: Exclusivity. The brand is asking for \"Tech\" exclusivity. That's too broad. How do we narrow it down?", "answer": "" },
  { "question": "Subject: Re: Payment split. Since I'm signing with you, do I pay you out of my pocket, or do you take your cut before sending me the money?", "answer": "" },
  { "question": "Subject: Re: Agency intro. Hi Safwan, we’re launching a new AI tool. We want creators to review it, but we can't pay them unless they drive actual signups. Will your creators do this?", "answer": "" },
  { "question": "Subject: Re: Video placement. The creator's video is doing great, but it's age-restricted on YouTube so it's not getting recommended. We want a make-good video.", "answer": "" },
  { "question": "Subject: Re: Rates. If we book 5 creators through your agency at once, can we get a 20% bundle discount?", "answer": "" },
  { "question": "Subject: Re: Follow up. Safwan, it's been a week and we haven't received the draft from the creator. The deadline was yesterday. What's the status?", "answer": "" },
  { "question": "Subject: Re: Creator matching. We have $10,000 to spend by the end of the month. Which 2-3 creators on your roster can we book right now to hit that spend?", "answer": "" },
  { "question": "Subject: Re: Usage rights. The creator's integration was great. We want to renew the usage rights for another 6 months. What's the renewal fee?", "answer": "" },
  { "question": "Subject: Re: Creator side. Hey Safwan, the brand wants me to read a script that says their product is \"the fastest in the world\", but I know it's not. I don't want to lie to my audience.", "answer": "" },
  { "question": "Subject: Re: Affiliate. I have a 10% affiliate code with the brand. Can I also put that in the description of the sponsored video to double-dip on revenue?", "answer": "" },
  { "question": "Subject: Re: Sponsorship. The brand said the video didn't get enough clicks and is refusing to pay the final 50% invoice. Help!", "answer": "" },
  { "question": "Subject: Re: Pitching. Hey Safwan, I'm going to a tech conference next month. Are there any brands attending that you can pitch me for in-person activations?", "answer": "" }
];
